#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/p_dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if stest -dqr -n "$cache" $PATH; then
	[ ! -e "$cache" ] && stest -flx $PATH | sort -u | sed "s/^/0 /" > "$cache"
fi
IFS=' '

command="$(cat "$cache" | sort -k1 -n -r | sed "s/^[0-9]* //" | dmenu "$@" | tr -d '\n')"
echo "$command"
if [ -n "$command" ]; then
	ctr="$(grep " $command" "$cache" | grep -o "^[0-9]*")"
	echo "$ctr"
	if [ -z "$ctr" ]; then
		echo "add"
		echo "0 $command" >> "$cache"
	fi
	ctr=$((ctr+1))
	sed -i "s/^[0-9]* $command/$ctr $command/" "$cache"
	echo "$command" | ${SHELL:-"/bin/sh"} &
fi
